version: "3.0"

services:
  nms:
    image: alkimiorg/nms:1.0.151
    command: >
      bash -c
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logfile - &&
          python manage.py collectstatic --noinput "
          
    environment:
      - "NMS_API_KEY=AR12532DE@#GH&67GF24GH45532##FGG"
      - "BACKEND_ENDPOINT=https://alkimi-nodes-backend-dev-eyb6u.ondigitalocean.app"
      - "BACKEND_API_KEY=7154b898-61b9-4496-a894-69feb11e6ed4"
      - "SEEDLIST_FILE=https://seedlist-details.s3.eu-west-2.amazonaws.com/dev/"

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - /app/docker_pipes:/app/docker_pipes
