version: '3.0'

services:
  db:
    container_name: sqllite3_database
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes: 
      - nms-database:/root/db
    ports:
      - "9000:9000"
  nms:
      image: asesha68/nms:1.0.4
      ports:
        - "8000:8000"
volumes:
  nms-database: