version: "3.0"

services:
  nms:
    image: alkimiorg/nms:1.0.108
    command: >
      bash -c
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logfile - &&
          python manage.py collectstatic --noinput "
          
    environment:
      - "NMS_API_KEY=GFA2V8ZQDCORI86ZFDT13G6SYJEXSA93"
      - "BACKEND_ENDPOINT=https://alkiminodes-backend-production-jrlib.ondigitalocean.app"
      - "BACKEND_API_KEY=7154b898-61b9-4496-a894-69feb11e6ed4"
      - "SEEDLIST_FILE=https://seedlist-details.s3.eu-west-2.amazonaws.com/prod/"

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - /app/docker_pipes:/app/docker_pipes
