version: "3.0"

services:
  nms:
    image: alkimiorg/nms:1.0.155
    command: >
      bash -c
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logfile - &&
          python manage.py collectstatic --noinput "
          
    environment:
      - "NMS_API_KEY=E58YS7YHN8A5848Y5GC7SUAMNVFXJRZB"
      - "BACKEND_ENDPOINT=https://alkimi-nodes-backend-qa-tokpo.ondigitalocean.app"
      - "BACKEND_API_KEY=63513aaf-bc9e-454c-a4d0-5db3df37b70a"
      - "SEEDLIST_FILE=https://seedlist-details.s3.eu-west-2.amazonaws.com/qa/"

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - /app/docker_pipes:/app/docker_pipes
