version: '3.0'

services:
  nms:
    image: asesha68/nms:1.0.21
    command: >
      sh -cx "gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput"
    ports:
      - "8000:8000"
      - "19001:19001"
      - "19002:19002"
      - "19003:19003"
      - "19004:19004"
      - "80:80"
    volumes:
      #- ./databases/db.sqlite3:/Alkimi/databases/db.sqlite3
      - ./app/databases:/home/ubuntu/nms_project/database
      #- ./databases/db.sqlite3:/db.sqlite3
      - staticfiles:/app/static
      - /home/ubuntu:/home/ubuntu
      - /app/docker_pipes:/app/docker_pipes

volumes:
  staticfiles:
