version: "3.0"
services:
  nms:
    image: alkimiorg/nms:v1.2.42
    command: >
      bash -c
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logfile - &&
          python manage.py collectstatic --noinput "
          
    environment:
      - "NDATA1=GFA2V8ZQDCORI86ZFDT13G6SYJEXSA93"
      - "ENDPOINT1=https://labs-v2.alkimi.org"
      - "BDATA2=207f3836-6c20-4a0d-2020-c989207b2020"
      - "SEEDLIST_FILE=https://seedlist-details.s3.eu-west-2.amazonaws.com/prod/"
      - "ENDPOINT2=https://healthstatus.alkimi.org/alkimi/getToken"
      - "ENDPOINT3=https://healthstatus.alkimi.org/alkimi/produce-message"

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - ./nms_logs:/app/nms_logs
      - /app/docker_pipes:/app/docker_pipes
      - /home/ubuntu/L1_App:/app/type_1_key_file
