version: "3.0"

services:
  nms:
    image: alkimiorg/nms:v1.2.9.3
    command: >
      bash -c
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logfile - &&
          python manage.py collectstatic --noinput "
          
    environment:
      - "NDATA1=VFD68FP65NTYR6V4WE5DM2388BHA4UNI"
      - "ENDPOINT1=https://stg.labs-v2.alkimi.org"
      - "BDATA2=7154b898-61b9-4496-a894-69feb11e6ed4"
      - "SEEDLIST_FILE=https://seedlist-details.s3.eu-west-2.amazonaws.com/stg/"
      - "ENDPOINT2=http://staging-nms-health-listener-env-env.eba-t9umxbqu.eu-west-2.elasticbeanstalk.com/alkimi/getToken"
      - "ENDPOINT3=http://staging-nms-health-listener-env-env.eba-t9umxbqu.eu-west-2.elasticbeanstalk.com/alkimi/produce-message"

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - ./nms_logs:/app/nms_logs
      - /app/docker_pipes:/app/docker_pipes
