version: "3.0"
services:
  nms:
    image: alkimiorg/nms:v1.2.19
    command: >
      bash -c
          "python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn --bind 0.0.0.0:8000 nms_project_settings.wsgi:application --access-logfile - &&
          python manage.py collectstatic --noinput "

    environment:
      - "NDATA1=AR12532DE@#GH&67GF24GH45532##FGG"
      - "ENDPOINT1=https://dev.labs-v2.alkimi.org"
      - "BDATA2=f698d1b3-19e1-4b9d-a81d-06b0a1a85819"
      - "SEEDLIST_FILE=https://seedlist-details.s3.eu-west-2.amazonaws.com/dev/"
      - "ENDPOINT2=http://dev-nms-health-listener-env.eba-cmywgxma.eu-west-2.elasticbeanstalk.com/alkimi/getToken"
      - "ENDPOINT3=http://dev-nms-health-listener-env.eba-cmywgxma.eu-west-2.elasticbeanstalk.com/alkimi/produce-message"

    network_mode: "host"
    volumes:
      - ./app/databases:/home/ubuntu/nms_project/database
      - /app/static:/app/static
      - /home/ubuntu:/home/ubuntu
      - ./nms_logs:/app/nms_logs
      - /app/docker_pipes:/app/docker_pipes
      - /home/ubuntu/L1_App:/app/type_1_key_file
